name: ScenarioMix
version: "1.1.0"
authors: [7isenko, hevav]
api-version: 1.20
main: io.github._7isenko.scenariomix.ScenarioMix
commands:
  mix:
    description: Открывает меню сценариев
    usage: /mix или /mix <сценарий> <конфиг> <значение>
    permission: scenariomix.menu
permissions:
  scenariomix.menu:
    default: op
    description: Открывать меню сценариев
  scenariomix.tools:
    default: op
    description: Использовать инструменты с плагина
  scenariomix.debug:
    default: op
    description: Показывать сообщения отладки